### ISSUE TITLE
getting error 

### ISSUE THREAD

**Issue by masoodazhar** [misbah4064/licensePlateReader#1]
i have installed all things

Installing collected packages: pytesseract
Successfully installed pytesseract-0.3.6

but geeting this error

(python380Env) D:\AI\licensePlateReader-master>py licensePlateDetection.py
Traceback (most recent call last):
  File "D:\Env\python380Env\lib\site-packages\pytesseract\pytesseract.py", line 250, in run_tesseract
    proc = subprocess.Popen(cmd_args, **subprocess_args())
  File "c:\users\masoo\appdata\local\programs\python\python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\masoo\appdata\local\programs\python\python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "licensePlateDetection.py", line 40, in <module>
    text = pytesseract.image_to_string(license_plate)
  File "D:\Env\python380Env\lib\site-packages\pytesseract\pytesseract.py", line 370, in image_to_string
    return {
  File "D:\Env\python380Env\lib\site-packages\pytesseract\pytesseract.py", line 373, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "D:\Env\python380Env\lib\site-packages\pytesseract\pytesseract.py", line 282, in run_and_get_output
    run_tesseract(**kwargs)
  File "D:\Env\python380Env\lib\site-packages\pytesseract\pytesseract.py", line 254, in run_tesseract
    raise TesseractNotFoundError()
pytesseract.pytesseract.TesseractNotFoundError: tesseract is not installed or it's not in your PATH. See README file for more information.

**Comment by nikunjkothiya** [comment]
@masoodazhar 
First of all install the tesseract-OCR engine in your system means in your os like a software install on the system. After that debug your program in pycharm and from that hover on a script where  highlight unfound variable and right-click on it to open __init__ file name as pytesseract.py file and find tesseract_cmd.
set path like :-> tesseract_cmd = 'C:\\Program Files\\Tesseract-OCR\\tesseract.exe'
I hope this will help you.

**Comment by Pami99** [comment]
I have installed all requirements but I keep getting this error. 
license_plate = cv2.bilateralFilter(license_plate, 11, 17, 17)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-6sxsq0tp\opencv\modules\imgproc\src\bilateral_filter.dispatch.cpp:409: error: (-215:Assertion failed) !_src.empty() in function 'cv::bilateralFilter'

Can you help me out?

**Comment by nikunjkothiya** [comment]
This happens sometimes due to incorrect versions of different libraries
like NumPy. PLease verify that Numpy version should be less than 1.16.1
with opencv.
After this if getting the same error than plase debug program step by step
and see bilateralFilter function get required parameters with required type
input img or not.
I personally used this technique for this type of problems.
I hope this will help you.
Thak you
